workspace(name = "examples_verify_versions")

local_repository(
    name = "dpu_rules_pyenv",
    path = "../../",
)

load("@dpu_rules_pyenv//pyenv:defs.bzl", "pyenv_install")

pyenv_install(
    hermetic = False,
    py2 = "2.7.17",
    py3 = "3.7.7",
)
