package(default_visibility = ["//visibility:public"])

py_binary(
    name = "main",
    srcs = ["main.py"],
    python_version = "PY3",
)

filegroup(
    name = "srcs",
    srcs = [
        "BUILD",
        "WORKSPACE",
        "main.py",
    ],
)
